### ISSUE TITLE
Typo in Lecture 2

### ISSUE THREAD

**Issue by tojiboyevf** [SkoltechAI/Perception-in-Robotics-course-T3-2022-Skoltech#1]
I think there is a typo in lecture 2. 
![image](https://user-images.githubusercontent.com/52247758/152090644-0c32ab55-f6a2-4a34-bb9c-7b0e822aad9b.png)
The last matrix `A` in `$A Sigma_x A$` should have a transpose

**Comment by KonstantinPakulev** [comment]
Thank you. Fixed.
