### ISSUE TITLE
Another typo in lecture 2

### ISSUE THREAD

**Issue by tojiboyevf** [SkoltechAI/Perception-in-Robotics-course-T3-2022-Skoltech#2]
![image](https://user-images.githubusercontent.com/52247758/152092492-64815f10-6823-4b36-8fbd-eb632f8fe205.png)
Typo in Taylor series

**Comment by tojiboyevf** [comment]
> ![image](https://user-images.githubusercontent.com/52247758/152092492-64815f10-6823-4b36-8fbd-eb632f8fe205.png) Typo in Taylor series

![image](https://user-images.githubusercontent.com/52247758/152093553-d891941d-ec6e-4aef-8b67-4667b0db19c4.png)

Here is the correct one

**Comment by KonstantinPakulev** [comment]
Fixed.
